In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import StandardScaler

dataset=pd.read_csv('data.csv')

data = pd.read_csv("data.csv")



In [3]:
dataset.head()

timestamp  act379  act13  act279  act323  act363  act302   latitude  \
0  28-02-2018 21:00       1      0       0       0       0       0  22.737260   
1  28-02-2018 21:15       1      0       0       0       0       0  22.720992   
2  28-02-2018 10:15       0      0       1       0       0       0  22.736676   
3  28-02-2018 10:15       0      0       1       0       0       0  22.746527   
4  28-02-2018 10:30       0      0       1       0       0       0  22.769531   

   longitude  
0  75.875987  
1  75.876083  
2  75.883168  
3  75.887139  
4  75.888772

In [4]:
data['timestamp'] = pd.to_datetime(data['timestamp'], errors='coerce',dayfirst=True)

In [5]:
data['timestamp']

0      2018-02-28 21:00:00
1      2018-02-28 21:15:00
2      2018-02-28 10:15:00
3      2018-02-28 10:15:00
4      2018-02-28 10:30:00
               ...        
2085                   NaT
2086                   NaT
2087                   NaT
2088                   NaT
2089                   NaT
Name: timestamp, Length: 2090, dtype: datetime64[ns]

In [6]:
# Assuming 'data' is your DataFrame containing the datetime column
column_1 = data.iloc[:, 0]

# Create a new DataFrame containing date and time components
db = pd.DataFrame({
    "year": column_1.dt.year,
    "month": column_1.dt.month,
    "day": column_1.dt.day,
    "hour": column_1.dt.hour,
    "dayofyear": column_1.dt.dayofyear,
    "week": column_1.dt.isocalendar().week,  # Using isocalendar().week
    "weekofyear": column_1.dt.isocalendar().week,  # Using isocalendar().week
    "dayofweek": column_1.dt.dayofweek,
    "weekday": column_1.dt.weekday,
    "quarter": column_1.dt.quarter
})

In [7]:
dataset1=dataset.drop('timestamp',axis=1)

In [8]:
data1=pd.concat([db,dataset1],axis=1)

In [9]:
data1.dropna(inplace=True)

In [10]:
data1.head()

year  month   day  hour  dayofyear  week  weekofyear  dayofweek  weekday  \
0  2018.0    2.0  28.0  21.0       59.0     9           9        2.0      2.0   
1  2018.0    2.0  28.0  21.0       59.0     9           9        2.0      2.0   
2  2018.0    2.0  28.0  10.0       59.0     9           9        2.0      2.0   
3  2018.0    2.0  28.0  10.0       59.0     9           9        2.0      2.0   
4  2018.0    2.0  28.0  10.0       59.0     9           9        2.0      2.0   

   quarter  act379  act13  act279  act323  act363  act302   latitude  \
0      1.0       1      0       0       0       0       0  22.737260   
1      1.0       1      0       0       0       0       0  22.720992   
2      1.0       0      0       1       0       0       0  22.736676   
3      1.0       0      0       1       0       0       0  22.746527   
4      1.0       0      0       1       0       0       0  22.769531   

   longitude  
0  75.875987  
1  75.876083  
2  75.883168  
3  75.887139  
4  75.888772

In [11]:
X=data1.iloc[:,[1,2,3,4,6,16,17]].values

In [12]:
X

array([[2.0, 28.0, 21.0, ..., 9, 22.73726, 75.875987],
       [2.0, 28.0, 21.0, ..., 9, 22.720992, 75.876083],
       [2.0, 28.0, 10.0, ..., 9, 22.736676, 75.883168],
       ...,
       [2.0, 28.0, 17.0, ..., 9, 22.705097, 75.888405],
       [2.0, 28.0, 20.0, ..., 9, 22.692111, 75.867548],
       [2.0, 28.0, 15.0, ..., 9, 22.693141, 75.827293]], dtype=object)

In [13]:
y=data1.iloc[:,[10,11,12,13,14,15]].values

In [14]:
y

array([[1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       ...,
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0]], dtype=int64)

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=50)

In [17]:

model = RandomForestClassifier(n_estimators=100, random_state=42)

# Step 7: Train the Model
model.fit(X_train, y_train)

# Step 8: Evaluate the Model
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

# Optional: Hyperparameter Tuning (if needed)

# Step 9: Deployment (if needed)


[[0 0 0 1 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 1 0 0 0 0]
 [0 0 0 1 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 1 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 1 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 0 1 0 0 0]
 [0 0 1 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [1 0 0 0 0 0]
 [0 0 0 1 0 0]
 [0 1 0 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 1 0 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [1 0 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 1 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 1 0]
 [0 1 0 0 0 0]
 [0 0 0 1 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 1 

C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifi

In [20]:
# Input data
import numpy as np
input_values = [2.0, 28.0, 21.0, 59.0, 9, 22.737260, 75.875987]

# Convert input values to a numpy array
input_values = np.array(input_values).reshape(1, -1)

# Now, you can use your trained model to make predictions on this input data
y_pred_input = model.predict(input_values)
print("Predicted activities:", y_pred_input)

Predicted activities: [[1 0 0 0 0 0]]


In [22]:
import pickle

# Save the model
with open('crime_prediction_model.pkl', 'wb') as f:
    pickle.dump(model, f)
